project:
  type: website
  output-dir: docs

website:
  title: "<b>희타민</b> 바보"
  navbar:
    background: '#0F1B38'
    left:
      - href: index_proj.qmd
        text: Projects
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

