project:
  type: website
  output-dir: docs

website:
  title: "최희승 블로그 만드는거 도와주기"
  navbar:
    background: '#0F1B38'
    left:
      - href: index_proj.qmd
        text: Projects
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

